# Generated by Django 3.1 on 2020-08-16 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='description_id',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='first.descriptin'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='name_manager',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя менеджера'),
        ),
    ]
